package com.libtop.weitu.dao.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig bookDaoConfig;

    private final SearchDao searchDao;
    private final HistoryDao historyDao;
    private final BookDao bookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        searchDao = new SearchDao(searchDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);

        registerDao(Search.class, searchDao);
        registerDao(History.class, historyDao);
        registerDao(Book.class, bookDao);
    }
    
    public void clear() {
        searchDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        bookDaoConfig.getIdentityScope().clear();
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

}
